### ISSUE TITLE
SmartOS 5.11 - CloudLinux 6.6 problems hungs

### ISSUE THREAD

**Issue by adhioutlined** [joyent/smartos-live#397]
Hi everyone, 

I've Installed CloudLinux 6.6 as KVM guest in SmartOS 5.11, using with cPanel. 
This is information about my SmartOS
```
# uname -a
SunOS gz1  5.11 joyent_20141030T164802Z i86pc i386 i86pc
```
This is information about CloudLinux I installed as KVM guest
```
# cat /etc/redhat-release
CloudLinux Server release 6.6 (Leonid Kizim)
# uname -r
2.6.32-531.29.2.lve1.3.11.1.el6.x86_64
```
everything was fine after VM installed for around 6 days until 2 days ago the CloudLinux VM was suddenly hungs, and works fine again after rebooted,  couple minutes ago its happened again and give a message on my ssh console 
```
Message from syslogd@jagalan at Feb 13 09:02:19 ..
kernel:[45516.131642] BUG: soft lockup - CPU#1 stuck for 67s! [grep:136248]
```
also from last night on the VNC console display about something like kernel panic
![hungs](https://s3-ap-southeast-1.amazonaws.com/uploads-ap.hipchat.com/19440/221518/mApRZOILJlZVGE4/Screen%20Shot%202015-02-12%20at%208.23.18%20PM.png)
Is there means a problem with CloudLinux Kernel or the problems come from Hypervisors (SmartOS) ?

**Comment by bahamat** [comment]
This looks to me like a bug in the Linux kernel which was fixed in [this commit](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=f06590bd718ed950c98828e30ef93204028f3210) and is available in 2.6.38 and later.

I'm not entirely familiar with CloudLinux, but judging by your kernel version (`2.6.32`, with patches) it's likely the same issue. I would start first with updating your kernel to at least 2.6.38.

**Comment by adhioutlined** [comment]
I'll try your suggestion @bahamat

**Comment by lloydde** [comment]
Closing for now.
