### ISSUE TITLE
installer creates invalid dump zvol, prevents system boot

### ISSUE THREAD

**Issue by failedrequest** [joyent/smartos-live#484]
The current code for smartos_prompt_config.sh in the function create_dump fails to set the dump zvol to a size suitable for dumpadm to work with.  As a result svc:/system/filesystem/smartdc:default fails to start yells about this.

 svc:/system/filesystem/smartdc:default (Joyent file system mounts)
  See: /etc/svc/volatile/system-filesystem-smartdc:default.log
 + zpool set feature@multi_vdev_crash_dump=enabled zones
+ dumpadm -y -d /dev/zvol/dsk/zones/dump
+ to small to hold a system dumpdump size 5151584256 bytes, device size 4294967296 bytes
 + fatal 'failed to configure dump device'
+ echo 'Error: failed to configure dump device'
Error: failed to configure dump device

After some testing it appears that setting the dump zvol to a 14G volsize or larger makes the check work and the system complete a bootup. 

This was noted on platfom images 20150423T155306Z and newer .

**Comment by nshalman** [comment]
In conversation on IRC @rmustacc's response to my suggestion of using the code from [joysetup.sh#L361-375](https://github.com/joyent/sdc-headnode/blob/89e7d2dc747a68e85d9f2aee5202cada44cdae03/scripts/joysetup.sh#L361-L375),  was: "Probably something like that, though constraining it based on some amount of available disk as well for smartos."

**Comment by failedrequest** [comment]
I would say rather then waste the disk space make the cap 32G for now or 33% the ram .

**Comment by failedrequest** [comment]
All
 I reviewed the issue on a fresh install. This is what the installer errors out with on the latest platform image 20150929T222233Z


<pre>
Creating pool zones...                                  done
Making dump zvol...                                     dumpadm: dump device /dev/zvol/dsk/zones/dump is too small to hold a system dump
dump size 5715423232 bytes, device size 4294967296 bytes
</pre>

That warning is from dumpadm , If the installer were to run dumpadm -e to get a dump volsize and then set it according to a multiple of the zfs blocksize then we end up with a working setup. 

So in the above noted case setting the volsize to 6G , ( Rounding 5.38G  up to 5.53G here ) works . Also it should be noted that dumpadm is setup to only collect kernel pages by default so we don't need a large dump vol . If someone were to change dumpadm to all , then it also up to them to set the dump volsize to 50% of the ram to hold the full dump.


Here is my proposed change 

<pre>
create_dump()
{

local raw_dumpsize=` echo "( \`dumpadm -e |  sed "s/[^0-9|.]//g"\` * 1024)" |bc`

local roud_dumpsize=`printf %0.f $raw_dumpsize`


 zfs create -V ${roud_dumpsize}mb -o checksum=noparity ${SYS_ZPOOL}/dumps || \
        fatal "failed to create the dump zvol"

}

</pre>

**Comment by jclulow** [comment]
Merged.

**Comment by Adel-Magebinary** [comment]
This problem still exists with the latest release when boot CN with pxe

**Comment by failedrequest** [comment]
Hello
  Can you send me a screen shot of where the installer breaks ? Also can you post the output from zpool status -v

**Comment by Adel-Magebinary** [comment]
Hello Mark,

I don't have the screenshots anymore for the issue. However, the issue was
setting a wrong size of dump.

I have to manually fix it with *zfs set volsize=HALF_SIZE_OF_SERER_RAM
zones/dump*


Kind Regards,

[+]Adel Abula
 [-] Founder | Solution Architect
 [-] PH:+64-09-9722636 | MOB:+64-212888791
 [-] Email: Adel@magebinary.com | Web: www.MageBinary.co.nz
<http://www.magebinary.co.nz/>
 [-] 11/145 Kitchener Rd, Milford, Auckland 0620 |



LinkedIn
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs64QZnvW1qf-3x1qwykgN6HcQ3S1G3X-f4-CsCC03?t=https%3A%2F%2Fwww.linkedin.com%2Fprofile%2Fview%3Fid%3D200823965&si=5556345204375552&pi=7d37b874-5715-4eda-c0c6-a6e8ac3bb1f4>
 | *Facebook <https://www.facebook.com/MageBinary>* | *Twitter*


IMPORTANT  NOTICE: The information contained in this file is confidential
and may  also be LEGALLY PRIVILEGED, intended only for the addressee. If
you are  not the addressee, any use or dissemination of the information
and/or  copying of this file is strictly prohibited. If you are not the
addressee, please immediately notify us.CONDITIONS:  MageBinary accepts no
liability or responsibility whatsoever for any  loss or damage suffered by
the recipient arising out of, or in  connection with, the use or misuse of
this data. All reasonable means  have been used by MageBinary to ensure
that the transfer medium and its  contents are free of computer viruses.
The copyright of the original  documentation belongs to MageBinary.

**Comment by failedrequest** [comment]
Interesting. There appears to be an new issue. This was observed on a dual disk setup running pxe booted platform-20160512T071413Z
```

 SmartOS Setup                           
 Storage                                        http://wiki.smartos.org/install
--------------------------------------------------------------------------------
SmartOS will automatically determine what we think is
the best zpool layout from your current disks. You may use this
suggestion, change to another built in storage profile, or simply create
your own zpool.
/smartdc/lib/smartos_prompt_config.sh: line 716: /var/tmp/mydisks: No such file or directory
/smartdc/lib/smartos_prompt_config.sh: line 717: /var/tmp/disklayout.json: No such file or directory
/smartdc/lib/smartos_prompt_config.sh: line 718: /var/tmp/disklayout.json: No such file or directory
json: error: could not read "/var/tmp/disklayout.json": Error: ENOENT, no such file or directory '/var/tmp/disklayout.json'


This is the 'default' storage configuration. To use it, type 'yes'.
 To see a different configuration, type: 'raidz2', 'mirror', or 'default'.
 To specify a manual configuration, type: 'manual'.
```

**Comment by failedrequest** [comment]
Looks like /var/tmp is missing in the live env . ```root@ /]# ls /var/tmp
/var/tmp: No such file or directory``

**Comment by failedrequest** [comment]
Swapping back to the prior platform version resolved this issue. This is 20160504T205801Z

`` SmartOS Setup                           
 Storage                                        http://wiki.smartos.org/install
--------------------------------------------------------------------------------
SmartOS will automatically determine what we think is
the best zpool layout from your current disks. You may use this
suggestion, change to another built in storage profile, or simply create
your own zpool.
vdevs: mirror c0t4d0 c0t5d0 total capacity: 931.51 GB

This is the 'default' storage configuration. To use it, type 'yes'.
 To see a different configuration, type: 'raidz2', 'mirror', or 'default'.
 To specify a manual configuration, type: 'manual'.




``

**Comment by failedrequest** [comment]
Created https://github.com/joyent/smartos-live/issues/628
