### ISSUE TITLE
Setup without disks is poorly handled, infinite loop in smartos_prompt_config.sh

### ISSUE THREAD

**Issue by loli10K** [joyent/smartos-live#711]
I've stumbled upon this by pure coincidence: i've been chasing a ZFS bug for quite some time now, and SmartOS is a very fast way for me to test Illumos ZFS without having to compile from source the whole thing: i'm just creating a bunch of virtual machines to find the version that introduced the change in ZFS i'm interested in.

On one of these machines i forgot to add a separate "data" disk, the result is an infinite loop in the configuration script:

```
 SmartOS Setup                           
 Storage                                        http://wiki.smartos.org/install
--------------------------------------------------------------------------------
SmartOS will automatically determine what we think is
the best zpool layout from your current disks. You may use this
suggestion, change to another built in storage profile, or simply create
your own zpool.
json: error: input is not JSON: Expected 'l' instead of 't' at line 1, column 3:
        fatal error: no primary storage disks available
        ..^
fatal error: no primary storage disks available
json: error: input is not JSON: Expected 'l' instead of 't' at line 1, column 3:
        fatal error: no primary storage disks available
        ..^
fatal error: no primary storage disks available
json: error: input is not JSON: Expected 'l' instead of 't' at line 1, column 3:
        fatal error: no primary storage disks available
        ..^
fatal error: no primary storage disks available
^C

Bringing up a shell.  When you are done in the shell hit ^D to
return to the system configuration tool.

[root@ /]# diskinfo -Hp
ATA     c2d0    -       -       1999872000      no      no
[root@ /]# fstyp -v /dev/dsk/c2d0p1
pcfs
Bytes Per Sector  512           Sectors Per Cluster    1
Reserved Sectors  32            Number of FATs         2
Root Dir Entries  0             Number of Sectors      0
Sectors Per FAT   0             Sectors Per Track      600
Number of Heads   1             Number Hidden Sectors  600
Volume ID: 0x0
Volume Label: SMARTOSBOOT
Drive Number: 0x80
Media Type: 0xf8   "Fixed" Disk
[root@ /]# uname -a
SunOS  5.11 joyent_20170315T210557Z i86pc i386 i86pc
[root@ /]#
```

This is just FYI, it's probably just a "cosmetic" issue.

**Comment by Ingramz** [comment]
While trying to set up SmartOS on one of my machines, I encountered the same problem. The JSON formatting error distracted me from the actual issue which is repeated within the output: `fatal error: no primary storage disks available` that originates from executing [ `disklayout`](https://github.com/joyent/smartos-live/blob/64998c0b5a7c33287eb7dd118fef4aea42e5a6f3/overlay/generic/smartdc/lib/smartos_prompt_config.sh#L731).

Although I do not have any interest in trying SmartOS before I find myself a disk controller that is supported (which was the underlying problem in my case), I propose monitoring the exit code of `disklayout` before trying to parse its output as JSON. Also because that command returns an error, it gets repeated due to the infinte loop wanting to try it again, which quickly scrolls away the introductory text, so it's hard to see what it even tried to do.

**Comment by rmustacc** [comment]
We've been working on a fix for this in: https://cr.joyent.us/#/c/1771/.

**Comment by rmustacc** [comment]
This should be resolved in https://github.com/joyent/smartos-live/commit/457eeeba252741ce02f8aae1444393c10f4d2e2c.
