### ISSUE TITLE
"Oops, mp_limb_t doesn't seem to work"

### ISSUE THREAD

**Issue by danielkasza** [joyent/smartos-live#721]
I tried to build SmartOS using [the instructions on the wiki](https://wiki.smartos.org/display/DOC/Building+SmartOS+on+SmartOS). The build fails with a variety of errors. The first one is in the title. The full `gmake live` output can be found [here](https://gist.github.com/danielkasza/8e02a2429397ab5230fd8a543af94532).

VM used:
````
{  
  "brand":"joyent",
  "fs_allowed":"ufs,pcfs,tmpfs",
  "max_physical_memory":4096,
  "quota":0,
  "image_uuid":"e69a0918-055d-11e5-8912-e3ceb6df4cf8",
  "resolvers":[  
    "8.8.8.8",
    "8.8.4.4"
  ],
  "nics":[  
    {  
      "interface":"net0",
      "nic_tag":"admin",
      "ip":"dhcp"
    }
  ]
}
````

**Comment by jperkin** [comment]
This is the real error:

```
/usr/include/stddef.h:36:24: fatal error: sys/stddef.h: No such file or directory
```

and is caused by a bad platform build recently which didn't install that header.  The way to fix this is to roll back to a platform from a couple of weeks ago, rebuild the latest smartos-live which will include a fix, then install that new platform and continue from there.

**Comment by danielkasza** [comment]
I downloaded the latest iso using the link on the [wiki](https://wiki.smartos.org/display/DOC/Download+SmartOS).
Is that the broken build? Is there a build that is known to work?
