### ISSUE TITLE
omnios vm running in bhyve broke between 20180802T002654Z and 20180830T063924Z

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#803]
It now panics because the vioblk device changed ordering it seems.

**Comment by sjorge** [comment]
@mgerdts only thing I can see effecting this would be moving bootrom from slot 0 to slot 32 for windows?

**Comment by mgerdts** [comment]
Additionally, the root disk moved to another slot so that any AHCI disks
will be in slots that are compatible with Windows, according to
https://wiki.freebsd.org/bhyve/Windows .

For those with ZFS root, it seems you will need to

1. Boot from an iso image.
2. Within the guest, zpool import -f rpool
3. zpool export rpool
4. shutdown
5. Remove the iso from the config
6. Boot the guest.

I have not yet verified this, but past experience with Solaris (where I
made root pool import more tolerant of shuffled disks) suggests this should
get past this hump.

Sorry for the troubles.
Mike

**Comment by sjorge** [comment]
Yeah I booted a smartos-live.iso (because those attached to ttya) and basically did that.

Good news is that the FreeBSD vm are not effected by this. Are the linux ones? (I am not running any)

**Comment by mgerdts** [comment]
Linux (centos 6, centos 7, debian 8, ubuntu 16.04) seem to be tolerant of
the shuffle.
